# Generated by Django 4.2.6 on 2023-11-23 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_alter_usergroup_options_remove_apiuser_usertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstore',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock_app.product'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тип пользователя'),
        ),
    ]
