# Generated by Django 4.2.6 on 2023-11-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_alter_productinstore_product_alter_usergroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstore',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Кол-во на складе'),
        ),
    ]
